services:
  server:
    image: microservice-schedule:latest
    container_name: microservice-schedule
    ports:
      - "8001:8001"
    environment:
      - ASPNETCORE_HTTPS_PORTS=8001
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ${APPDATA}/microsoft/UserSecrets/:/home/app/.microsoft/usersecrets
      - ${USERPROFILE}/.aspnet/https/:/https/
    stdin_open: true
    tty: true
    build:
      context: .
      target: final
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
