openapi: 3.0.4
info:
  title: Расписание
  description: 
    Сервис Расписания.
  version: 0.1.0
servers:
  - url: toDo
tags:
  - name: Расписание
    description: Получение расписания
  - name: Уроки
    description: Редактирование уроков
paths:
  /schedule:
    get:
      tags:
        - Расписание
      summary: Получение сводного расписания.
      description: Получение сводного расписания за выбранный период.
      parameters:
        - name: period
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/period'
      responses: 
        "200": 
          description: Сводное расписание на неделю.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/schedule'
        "400": 
          description: неверные параметры запроса
        '412':
          description: начало урока позже конца
                
  /schedule/user:
    get:
      tags:
        - Расписание
      summary: Получение расписания пользователя.
      description: Получение расписания пользователя за выбранный период.
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
        - name: type
          description: класс - 1 или учитель - 0.
          in: query
          required: true
          schema:
            type: boolean 
        - name: period
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/period'
      responses:
        "200": 
          description: Сводное расписание на неделю.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/schedule'
        "400": 
          description: неверные параметры запроса
        '404':
          description: расписание не найдено
        '412':
          description: начало урока позже конца
          
          
  /lesson:
    post:
      tags:
        - Уроки
      summary: Добавить урок.
      parameters:
        - name: Данные урока.
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/lessons"
      responses:
        "200": 
          description: урок сохранен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lessonCreate'
    delete:
      tags:
        - Уроки
      summary: Удалить урок.
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: урок удален
        "400": 
          description: неверные параметры запроса
        '404':
          description: урок не найден
        
          
    patch:
      tags:
        - Уроки
      summary: Изменить урок.
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
        - name: Данные урока.
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/lesson"
      responses:
        "200": 
          description: изменения сохранены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lessonCreate'
        "400": 
          description: неверные параметры запроса
        '404':
          description: урок не найден
                
  /mark:
    post:
      tags:
        - Оценки
      summary: Выставить оценку.
      parameters:
        - name: Данные оценки.
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/mark"
      responses:
        '200':
          description: оценка выставлена
        "400": 
          description: неверные параметры запроса
        '412':
          description: учитель не имеет право высталять оценки за этот предмет
        
        
components:
  schemas:
          
    lesson:
      type: object
      properties:
        subject:
          type: string
        startTime: 
          type: string
        endTime: 
          type: string
        date:
          type: string
        className:
          type: string
        teacherId:
          type: string
        task:
          type: string
          
    lessons:
      type: object
      properties:
        subject:
          type: string
        startTime: 
          type: string
        endTime: 
          type: string
        startDate:
          type: string
        endDate:
          type: string
        dayWeek:
          type: array
          items:
            type: string
        className:
          type: string
        teacherId:
          type: string
        
    schedule:
      type: object
      properties:
        lessons:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/lesson'
          
    period:
      type: object
      properties:
        startTime: 
          type: string
        endTime: 
          type: string
        startDate:
          type: string
        endDate:
          type: string
        
    lessonCreate:
      type: object
      properties:
        id:
          type: array
          items:
            type: string
        
    mark:
      type: object
      properties:
        date: 
          type: string
        teacherId:
          type: string
        userid:
          type: string
        lessonid:
          type: string
        mark:
          type: string
        comment:
          type: string
